name: Daily Notion Template Automation

on:
  push:
  schedule:
    - cron: '0 6 * * *'  # Runs daily at 6 AM UTC
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  generate-and-post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai requests
          pip install google-generativeai
          pip install reportlab
          pip install selenium

      - name: Set up Chrome for Selenium
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-chromedriver
          sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver
          export CHROME_BIN=chromium-browser
          export PATH=$PATH:/usr/lib/chromium-browser/

      - name: Run Notion Script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GUMROAD_TOKEN: ${{ secrets.GUMROAD_TOKEN }}
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_PAGE_ID: ${{ secrets.NOTION_PAGE_ID }}  
          PINTEREST_TOKEN: ${{ secrets.PINTEREST_TOKEN }}
          GEN_API_KEY: ${{ secrets.GEN_API_KEY }}
        run: |
          python daily_notion_template_automation.py

      - name: Run Planner Automation Script
        env:
          GUMROAD_EMAIL: ${{ secrets.EMAIL }}
          GUMROAD_PASSWORD: ${{ secrets.GUMROAD_PASSWORD }}
        run: |
          python daily_planner_automation.py
